#############################################################################
# Makefile for building: bin/blockadeRunner
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  blockadeRunner.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile blockadeRunner.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DMODE_NORMAL -DNO_REPETE_EXPLOSION -DJEU_VERBOSE -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG
CFLAGS        = -m64 -pipe -g -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I. -I/usr/include
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS) -lSDL -lSDL_image -lSDL_ttf -lfmodex64 -lSDL_gfx -L/usr/LIBS 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/Animation.c \
		src/Audio.c \
		src/ElementScene.c \
		src/EntreeSDL.c \
		src/GraphiqueSDL.c \
		src/JeuSDL.c \
		src/Joueur.c \
		src/main.c \
		src/Menu.c \
		src/Niveau.c \
		src/Outils.c \
		src/Ressource.c \
		src/Scene.c \
		src/Vaisseau.c 
OBJECTS       = obj/Animation.o \
		obj/Audio.o \
		obj/ElementScene.o \
		obj/EntreeSDL.o \
		obj/GraphiqueSDL.o \
		obj/JeuSDL.o \
		obj/Joueur.o \
		obj/main.o \
		obj/Menu.o \
		obj/Niveau.o \
		obj/Outils.o \
		obj/Ressource.o \
		obj/Scene.o \
		obj/Vaisseau.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/declarative_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		blockadeRunner.pro \
		blockadeRunner.pro
QMAKE_TARGET  = blockadeRunner
DESTDIR       = bin/#avoid trailing-slash linebreak
TARGET        = bin/blockadeRunner


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: blockadeRunner.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/declarative_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		blockadeRunner.pro
	$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile blockadeRunner.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/declarative_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
blockadeRunner.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile blockadeRunner.pro

qmake_all: FORCE

dist: 
	@test -d obj/blockadeRunner1.0.0 || mkdir -p obj/blockadeRunner1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/blockadeRunner1.0.0/ && (cd `dirname obj/blockadeRunner1.0.0` && $(TAR) blockadeRunner1.0.0.tar blockadeRunner1.0.0 && $(COMPRESS) blockadeRunner1.0.0.tar) && $(MOVE) `dirname obj/blockadeRunner1.0.0`/blockadeRunner1.0.0.tar.gz . && $(DEL_FILE) -r obj/blockadeRunner1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) bin/$(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

obj/Animation.o: src/Animation.c /usr/include/assert.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		src/Animation.h \
		/usr/include/SDL/SDL.h \
		/usr/include/SDL/SDL_main.h \
		/usr/include/SDL/SDL_stdinc.h \
		/usr/include/SDL/SDL_config.h \
		/usr/include/SDL/SDL_platform.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/xlocale.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/stdlib.h \
		/usr/include/alloca.h \
		/usr/include/malloc.h \
		/usr/include/memory.h \
		/usr/include/string.h \
		/usr/include/strings.h \
		/usr/include/inttypes.h \
		/usr/include/stdint.h \
		/usr/include/iconv.h \
		/usr/include/SDL/begin_code.h \
		/usr/include/SDL/close_code.h \
		/usr/include/SDL/SDL_audio.h \
		/usr/include/SDL/SDL_error.h \
		/usr/include/SDL/SDL_endian.h \
		/usr/include/SDL/SDL_mutex.h \
		/usr/include/SDL/SDL_thread.h \
		/usr/include/SDL/SDL_rwops.h \
		/usr/include/SDL/SDL_cdrom.h \
		/usr/include/SDL/SDL_cpuinfo.h \
		/usr/include/SDL/SDL_events.h \
		/usr/include/SDL/SDL_active.h \
		/usr/include/SDL/SDL_keyboard.h \
		/usr/include/SDL/SDL_keysym.h \
		/usr/include/SDL/SDL_mouse.h \
		/usr/include/SDL/SDL_video.h \
		/usr/include/SDL/SDL_joystick.h \
		/usr/include/SDL/SDL_quit.h \
		/usr/include/SDL/SDL_loadso.h \
		/usr/include/SDL/SDL_timer.h \
		/usr/include/SDL/SDL_version.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/Animation.o src/Animation.c

obj/Audio.o: src/Audio.c /usr/include/assert.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/stdlib.h \
		/usr/include/xlocale.h \
		/usr/include/alloca.h \
		/usr/include/string.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		src/Audio.h \
		src/Ressource.h \
		src/Joueur.h \
		src/Vaisseau.h \
		src/Niveau.h \
		src/Outils.h \
		src/Scene.h \
		src/ElementScene.h \
		lib/inc/fmod.h \
		lib/inc/fmod_codec.h \
		lib/inc/fmod_dsp.h \
		lib/inc/fmod_memoryinfo.h \
		lib/inc/fmodlinux.h \
		lib/inc/fmod_errors.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/Audio.o src/Audio.c

obj/ElementScene.o: src/ElementScene.c /usr/include/stdio.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/xlocale.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/stdlib.h \
		/usr/include/alloca.h \
		/usr/include/assert.h \
		src/ElementScene.h \
		src/Vaisseau.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/ElementScene.o src/ElementScene.c

obj/EntreeSDL.o: src/EntreeSDL.c /usr/include/assert.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/stdlib.h \
		/usr/include/xlocale.h \
		/usr/include/alloca.h \
		src/EntreeSDL.h \
		/usr/include/SDL/SDL.h \
		/usr/include/SDL/SDL_main.h \
		/usr/include/SDL/SDL_stdinc.h \
		/usr/include/SDL/SDL_config.h \
		/usr/include/SDL/SDL_platform.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/malloc.h \
		/usr/include/memory.h \
		/usr/include/string.h \
		/usr/include/strings.h \
		/usr/include/inttypes.h \
		/usr/include/stdint.h \
		/usr/include/iconv.h \
		/usr/include/SDL/begin_code.h \
		/usr/include/SDL/close_code.h \
		/usr/include/SDL/SDL_audio.h \
		/usr/include/SDL/SDL_error.h \
		/usr/include/SDL/SDL_endian.h \
		/usr/include/SDL/SDL_mutex.h \
		/usr/include/SDL/SDL_thread.h \
		/usr/include/SDL/SDL_rwops.h \
		/usr/include/SDL/SDL_cdrom.h \
		/usr/include/SDL/SDL_cpuinfo.h \
		/usr/include/SDL/SDL_events.h \
		/usr/include/SDL/SDL_active.h \
		/usr/include/SDL/SDL_keyboard.h \
		/usr/include/SDL/SDL_keysym.h \
		/usr/include/SDL/SDL_mouse.h \
		/usr/include/SDL/SDL_video.h \
		/usr/include/SDL/SDL_joystick.h \
		/usr/include/SDL/SDL_quit.h \
		/usr/include/SDL/SDL_loadso.h \
		/usr/include/SDL/SDL_timer.h \
		/usr/include/SDL/SDL_version.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/EntreeSDL.o src/EntreeSDL.c

obj/GraphiqueSDL.o: src/GraphiqueSDL.c /usr/include/assert.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/xlocale.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/stdlib.h \
		/usr/include/alloca.h \
		/usr/include/string.h \
		/usr/include/SDL/SDL_image.h \
		/usr/include/SDL/SDL.h \
		/usr/include/SDL/SDL_main.h \
		/usr/include/SDL/SDL_stdinc.h \
		/usr/include/SDL/SDL_config.h \
		/usr/include/SDL/SDL_platform.h \
		/usr/include/malloc.h \
		/usr/include/memory.h \
		/usr/include/strings.h \
		/usr/include/inttypes.h \
		/usr/include/stdint.h \
		/usr/include/iconv.h \
		/usr/include/SDL/begin_code.h \
		/usr/include/SDL/close_code.h \
		/usr/include/SDL/SDL_audio.h \
		/usr/include/SDL/SDL_error.h \
		/usr/include/SDL/SDL_endian.h \
		/usr/include/SDL/SDL_mutex.h \
		/usr/include/SDL/SDL_thread.h \
		/usr/include/SDL/SDL_rwops.h \
		/usr/include/SDL/SDL_cdrom.h \
		/usr/include/SDL/SDL_cpuinfo.h \
		/usr/include/SDL/SDL_events.h \
		/usr/include/SDL/SDL_active.h \
		/usr/include/SDL/SDL_keyboard.h \
		/usr/include/SDL/SDL_keysym.h \
		/usr/include/SDL/SDL_mouse.h \
		/usr/include/SDL/SDL_video.h \
		/usr/include/SDL/SDL_joystick.h \
		/usr/include/SDL/SDL_quit.h \
		/usr/include/SDL/SDL_loadso.h \
		/usr/include/SDL/SDL_timer.h \
		/usr/include/SDL/SDL_version.h \
		/usr/include/SDL/SDL_rotozoom.h \
		/usr/include/math.h \
		src/GraphiqueSDL.h \
		/usr/include/SDL/SDL_ttf.h \
		src/Menu.h \
		src/Outils.h \
		src/Ressource.h \
		src/Joueur.h \
		src/Vaisseau.h \
		src/Niveau.h \
		src/Scene.h \
		src/ElementScene.h \
		src/Animation.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/GraphiqueSDL.o src/GraphiqueSDL.c

obj/JeuSDL.o: src/JeuSDL.c /usr/include/assert.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/stdlib.h \
		/usr/include/xlocale.h \
		/usr/include/alloca.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/time.h \
		src/JeuSDL.h \
		src/GraphiqueSDL.h \
		/usr/include/SDL/SDL.h \
		/usr/include/SDL/SDL_main.h \
		/usr/include/SDL/SDL_stdinc.h \
		/usr/include/SDL/SDL_config.h \
		/usr/include/SDL/SDL_platform.h \
		/usr/include/malloc.h \
		/usr/include/memory.h \
		/usr/include/string.h \
		/usr/include/strings.h \
		/usr/include/inttypes.h \
		/usr/include/stdint.h \
		/usr/include/iconv.h \
		/usr/include/SDL/begin_code.h \
		/usr/include/SDL/close_code.h \
		/usr/include/SDL/SDL_audio.h \
		/usr/include/SDL/SDL_error.h \
		/usr/include/SDL/SDL_endian.h \
		/usr/include/SDL/SDL_mutex.h \
		/usr/include/SDL/SDL_thread.h \
		/usr/include/SDL/SDL_rwops.h \
		/usr/include/SDL/SDL_cdrom.h \
		/usr/include/SDL/SDL_cpuinfo.h \
		/usr/include/SDL/SDL_events.h \
		/usr/include/SDL/SDL_active.h \
		/usr/include/SDL/SDL_keyboard.h \
		/usr/include/SDL/SDL_keysym.h \
		/usr/include/SDL/SDL_mouse.h \
		/usr/include/SDL/SDL_video.h \
		/usr/include/SDL/SDL_joystick.h \
		/usr/include/SDL/SDL_quit.h \
		/usr/include/SDL/SDL_loadso.h \
		/usr/include/SDL/SDL_timer.h \
		/usr/include/SDL/SDL_version.h \
		/usr/include/SDL/SDL_ttf.h \
		src/Menu.h \
		src/Outils.h \
		src/Ressource.h \
		src/Joueur.h \
		src/Vaisseau.h \
		src/Niveau.h \
		src/Scene.h \
		src/ElementScene.h \
		src/Animation.h \
		src/Audio.h \
		lib/inc/fmod.h \
		lib/inc/fmod_codec.h \
		lib/inc/fmod_dsp.h \
		lib/inc/fmod_memoryinfo.h \
		lib/inc/fmodlinux.h \
		lib/inc/fmod_errors.h \
		src/EntreeSDL.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/JeuSDL.o src/JeuSDL.c

obj/Joueur.o: src/Joueur.c /usr/include/stdlib.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/xlocale.h \
		/usr/include/alloca.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/assert.h \
		/usr/include/string.h \
		src/Joueur.h \
		src/Vaisseau.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/Joueur.o src/Joueur.c

obj/main.o: src/main.c /usr/include/stdio.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/xlocale.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		src/JeuSDL.h \
		src/GraphiqueSDL.h \
		/usr/include/SDL/SDL.h \
		/usr/include/SDL/SDL_main.h \
		/usr/include/SDL/SDL_stdinc.h \
		/usr/include/SDL/SDL_config.h \
		/usr/include/SDL/SDL_platform.h \
		/usr/include/stdlib.h \
		/usr/include/alloca.h \
		/usr/include/malloc.h \
		/usr/include/memory.h \
		/usr/include/string.h \
		/usr/include/strings.h \
		/usr/include/inttypes.h \
		/usr/include/stdint.h \
		/usr/include/iconv.h \
		/usr/include/SDL/begin_code.h \
		/usr/include/SDL/close_code.h \
		/usr/include/SDL/SDL_audio.h \
		/usr/include/SDL/SDL_error.h \
		/usr/include/SDL/SDL_endian.h \
		/usr/include/SDL/SDL_mutex.h \
		/usr/include/SDL/SDL_thread.h \
		/usr/include/SDL/SDL_rwops.h \
		/usr/include/SDL/SDL_cdrom.h \
		/usr/include/SDL/SDL_cpuinfo.h \
		/usr/include/SDL/SDL_events.h \
		/usr/include/SDL/SDL_active.h \
		/usr/include/SDL/SDL_keyboard.h \
		/usr/include/SDL/SDL_keysym.h \
		/usr/include/SDL/SDL_mouse.h \
		/usr/include/SDL/SDL_video.h \
		/usr/include/SDL/SDL_joystick.h \
		/usr/include/SDL/SDL_quit.h \
		/usr/include/SDL/SDL_loadso.h \
		/usr/include/SDL/SDL_timer.h \
		/usr/include/SDL/SDL_version.h \
		/usr/include/SDL/SDL_ttf.h \
		src/Menu.h \
		src/Outils.h \
		src/Ressource.h \
		src/Joueur.h \
		src/Vaisseau.h \
		src/Niveau.h \
		src/Scene.h \
		src/ElementScene.h \
		src/Animation.h \
		src/Audio.h \
		lib/inc/fmod.h \
		lib/inc/fmod_codec.h \
		lib/inc/fmod_dsp.h \
		lib/inc/fmod_memoryinfo.h \
		lib/inc/fmodlinux.h \
		lib/inc/fmod_errors.h \
		src/EntreeSDL.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/main.o src/main.c

obj/Menu.o: src/Menu.c /usr/include/stdlib.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/xlocale.h \
		/usr/include/alloca.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/string.h \
		/usr/include/assert.h \
		src/Menu.h \
		src/Outils.h \
		src/Ressource.h \
		src/Joueur.h \
		src/Vaisseau.h \
		src/Niveau.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/Menu.o src/Menu.c

obj/Niveau.o: src/Niveau.c /usr/include/stdlib.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/xlocale.h \
		/usr/include/alloca.h \
		/usr/include/assert.h \
		/usr/include/string.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		src/Ressource.h \
		src/Joueur.h \
		src/Vaisseau.h \
		src/Niveau.h \
		src/Outils.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/Niveau.o src/Niveau.c

obj/Outils.o: src/Outils.c /usr/include/assert.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/stdlib.h \
		/usr/include/xlocale.h \
		/usr/include/alloca.h \
		/usr/include/time.h \
		src/Outils.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/Outils.o src/Outils.c

obj/Ressource.o: src/Ressource.c /usr/include/stdlib.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/xlocale.h \
		/usr/include/alloca.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/assert.h \
		/usr/include/string.h \
		src/Ressource.h \
		src/Joueur.h \
		src/Vaisseau.h \
		src/Niveau.h \
		src/Outils.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/Ressource.o src/Ressource.c

obj/Scene.o: src/Scene.c /usr/include/stdlib.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/xlocale.h \
		/usr/include/alloca.h \
		/usr/include/assert.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/math.h \
		src/Scene.h \
		src/ElementScene.h \
		src/Ressource.h \
		src/Joueur.h \
		src/Vaisseau.h \
		src/Niveau.h \
		src/Outils.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/Scene.o src/Scene.c

obj/Vaisseau.o: src/Vaisseau.c /usr/include/stdlib.h \
		/usr/include/features.h \
		/usr/include/stdc-predef.h \
		/usr/include/xlocale.h \
		/usr/include/alloca.h \
		/usr/include/stdio.h \
		/usr/include/libio.h \
		/usr/include/_G_config.h \
		/usr/include/wchar.h \
		/usr/include/wctype.h \
		/usr/include/endian.h \
		/usr/include/gconv.h \
		/usr/include/getopt.h \
		/usr/include/ctype.h \
		/usr/include/assert.h \
		src/Vaisseau.h \
		src/Outils.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o obj/Vaisseau.o src/Vaisseau.c

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

